### PR TITLE
Support for the ".allow" whitelisting behavior

### PR DESCRIPTION
**Pull request by david-unergie**
A proposal for the issue: https://github.com/hapijs/joi-date-extensions/issues/13

### CODE REVIEW

**Comment by hueniverse** [comment]
@Marsup is the the right way to solve it? Feels like a bug in the extension system.

**Comment by Marsup** [comment]
It can be seen as a bug or a design decision. `valid` values happen after coercion, it felt logical at the time. I don't see a way around this kind of patch.

**Comment by hueniverse** [comment]
`coerce()` should not be returning errors on strings it cannot parse. It should just do its best to convert and return the input if it can't. Then valids will be checked, then the base rule will make sure the coerced value is valid. The issue is just with how this extension is written. This is not the write solution. The right one is not to error in `coerce()`.

**Comment by hueniverse** [comment]
This will be fixed in the joi v16 release. I'll let @Marsup decide if he wants to apply this patch to v15.

**Pull request closed without merging**
